HF backend refactor
clp-research/clemcore pull request #37
Opened 2024-01-26 23:41 UTC by Gnurro

Changes:
- Model settings are now stored in external JSON model registry
- Two new prototyping methods to check messages for issues and context limit
- General Exception to handle exceeding context
- Gated model (Llama2) handling integrated into single HF backend
- New and updated documentation

2024-01-31 15:27 UTC, phisad requested changes
See code comments

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +current_wd = os.getcwd()
I think it would be easier to use `backends.project_root` and assume a while with the name?

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +    model_registry_path = os.path.join("hf_local_models.json")
`os.path.join("hf_local_models.json")` seems like doing nothing?

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +with open(model_registry_path, 'r', encoding="utf-8") as model_registry_file:
No need to specify 'r' here.

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +SUPPORTED_MODELS = [model_setting['model_name'] for model_setting in MODEL_REGISTRY if model_setting['backend'] == NAME]
The file is called `hf_local_models.json`so I guess it is always `huggingface`?

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +        self.CACHE_DIR = os.path.join(root_data_path, "huggingface_cache")
At least on our servers this is `/data/huggingface` Could we make it configurable or a part of the registry entry?

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +        if 'slow_tokenizer' in self.model_settings:
Could be improved with

```
is_slow_tokenizer = self.model_settings.get("slow_tokenizer", false)
if is_slow_tokenizer:
   ...
```

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +            if 'custom_chat_template' in self.model_settings:
Could be improved with

```
custom_chat_template = self.model_settings.get("custom_chat_template", None)
if custom_chat_template:
   ...
```

No need for `premade_chat_template` flag ?

2024-01-31 15:27 UTC, phisad commented on backends/huggingface_local_api.py
> +            if response_text[-eos_len:len(response_text)] == self.model_settings['eos_to_cull']:
How about this

```
eos_to_cull = self.model_settings.get("eos_to_cull",None)
if eos_to_cull and response_text.endswith(eos_to_cull):
  ...
```

2024-01-31 15:59 UTC, Gnurro commented on backends/huggingface_local_api.py
> +current_wd = os.getcwd()
Oh, I must have overlooked that there's a function for that, will use that, then.

2024-01-31 16:00 UTC, Gnurro commented on backends/huggingface_local_api.py
> +    model_registry_path = os.path.join("hf_local_models.json")
It makes sure that it's a viable path when run on any OS.

2024-01-31 16:01 UTC, Gnurro commented on backends/huggingface_local_api.py
> +with open(model_registry_path, 'r', encoding="utf-8") as model_registry_file:
I like to fully specify open() statements, just to make sure and be consistent. If that coding style is an issue, I can change it.

2024-01-31 16:03 UTC, Gnurro commented on backends/huggingface_local_api.py
> +SUPPORTED_MODELS = [model_setting['model_name'] for model_setting in MODEL_REGISTRY if model_setting['backend'] == NAME]
Yeah, it might change when the registry overhaul you're working on gets added, though. This is employing the backend name constant that I've kept since I'm unsure if it gets used elsewhere as well, mainly.

2024-01-31 16:05 UTC, Gnurro commented on backends/huggingface_local_api.py
> +        self.CACHE_DIR = os.path.join(root_data_path, "huggingface_cache")
We could - but where will this setting be stored, then? An additional configuration file? The code above is made to make sure everything works just as before this refactor.

2024-01-31 16:06 UTC, Gnurro commented on backends/huggingface_local_api.py
> +        if 'slow_tokenizer' in self.model_settings:
My code does the exact same thing without the extra variable, and makes sure that the setting is in fact `true` to be more robust to user error.

2024-01-31 16:07 UTC, Gnurro commented on backends/huggingface_local_api.py
> +            if 'custom_chat_template' in self.model_settings:
Same as above.

2024-01-31 16:08 UTC, Gnurro commented on backends/huggingface_local_api.py
> +            if response_text[-eos_len:len(response_text)] == self.model_settings['eos_to_cull']:
Using proper string splits is more robust. And as `eos_to_cull` is mandatory, the extra variable and `get()` are redundant.

2024-01-31 20:57 UTC, phisad commented on backends/huggingface_local_api.py
> +        self.CACHE_DIR = os.path.join(root_data_path, "huggingface_cache")
But indeed on other machines the directory name is different, namely `huggingface`. So it would be nice to make this adjustable e.g. add it to the keys.json (like on url pointing to a backend server).

2024-01-31 20:59 UTC, phisad commented on backends/huggingface_local_api.py
> +            if 'custom_chat_template' in self.model_settings:
So when do you have `premade_chat_template` but not `custom_chat_template`? Is this a duplicate?

2024-01-31 21:00 UTC, phisad commented on backends/huggingface_local_api.py
> +            if response_text[-eos_len:len(response_text)] == self.model_settings['eos_to_cull']:
Ah, this comment was simply about the if in line 409. It reads way harder than an endswith checks. No need to fiddle with string lengths?!

2024-02-01 09:22 UTC, Gnurro commented on backends/huggingface_local_api.py
> +            if 'custom_chat_template' in self.model_settings:
When there is a premade template, `premade_chat_template` is `true` and there is no `custom_chat_template`.

2024-02-01 09:31 UTC, Gnurro commented on backends/huggingface_local_api.py
> +        self.CACHE_DIR = os.path.join(root_data_path, "huggingface_cache")
I'll look into how transformers/HF hub handles the cache folder so this can be done without breaking existing setups. This change was not at all planned, so it'll likely take some extra time to implement properly.

2024-02-01 09:32 UTC, Gnurro commented on backends/huggingface_local_api.py
> +            if response_text[-eos_len:len(response_text)] == self.model_settings['eos_to_cull']:
I'll change it to use endswith, for readability.

2024-02-01 10:39 UTC, Gnurro commented on backends/huggingface_local_api.py
> +current_wd = os.getcwd()
Resolved with https://github.com/clp-research/clembench/pull/37/commits/7ab04c69db464b7c81c0cd849c0a22426ce6a8e9

2024-02-01 10:40 UTC, Gnurro commented on backends/huggingface_local_api.py
> +    model_registry_path = os.path.join("hf_local_models.json")
Also resolved by https://github.com/clp-research/clembench/pull/37/commits/7ab04c69db464b7c81c0cd849c0a22426ce6a8e9

2024-02-01 10:41 UTC, Gnurro commented on backends/huggingface_local_api.py
> +            if response_text[-eos_len:len(response_text)] == self.model_settings['eos_to_cull']:
See https://github.com/clp-research/clembench/pull/37/commits/3dd9df4b9a8595c30819b2c0bfe264e799939441

2024-02-01 10:41 UTC, phisad commented on backends/huggingface_local_api.py
> +        self.CACHE_DIR = os.path.join(root_data_path, "huggingface_cache")
OK, that's true. I'll make the adjustments in the merged preview branch.

2024-02-01 10:42 UTC, phisad approved these changes

2024-02-01 10:51 UTC, merged