Add option to specify filename for instances in GameInstanceGenerator
clp-research/clemcore pull request #38
Opened 2024-01-29 16:36 UTC by AnneBeyer

As a first step towards #12, GameInstanceGenerator.generate() can now be given a file name to create different versions of instances in `in/` (default is set to "instances.json" as before)

2024-01-31 15:00 UTC, phisad commented on clemgame/clemgame.py
> +    def store(self, filename):
This method seems nowhere else used. Could you please inline it?

2024-01-31 15:01 UTC, phisad requested changes
Along the way we could inline the store method which is never used elsewhere

2024-02-06 08:13 UTC, AnneBeyer commented on clemgame/clemgame.py
> +    def store(self, filename):
Sure.

2024-02-06 15:40 UTC, phisad approved these changes

2024-02-06 16:08 UTC, closed without merging

2024-02-06 16:08 UTC, phisad commented
fixed with https://github.com/clp-research/clembench/pull/44