Llamacpp backend
clp-research/clemcore pull request #81
Opened 2024-04-18 15:48 UTC by Gnurro

`llama-cpp-python`-based backend to allow running GGUF/GGML models.

2024-04-19 11:59 UTC, phisad commented on backends/llamacpp_api.py
> +    if hasattr(model_spec, 'execute_on'):
might "device" be a more common attribute name? and like in pytorch "cuda" instead of "gpu"? this could actually be a useful attributes for all models

2024-04-19 12:00 UTC, phisad commented on backends/llamacpp_api.py
> +            gpu_layers_offloaded = -1
this seems unnecessary b.c. it is the default

2024-04-19 12:02 UTC, phisad commented on backends/llamacpp_api.py
> +                    # get BOS/EOS strings for chatml from llama.cpp:
the comment seems unnecessary

2024-04-19 12:04 UTC, phisad commented on backends/llamacpp_api.py
> +        for key, value in self.model.metadata.items():
why loop if it's a dict. better `self.context_length = metadata.get("context_length", 512)`

2024-04-19 12:08 UTC, phisad commented on backends/llamacpp_api.py
> +        self.chat_formatter = llama_cpp.llama_chat_format.Jinja2ChatFormatter(
I suggest to extract a `load_formatter` method wich goes below `load_model` and a test_case for loading a formatter. And `self.bos_string` also seems not to be accessed anymore after this line, so why in `self`?

2024-04-19 12:13 UTC, phisad commented on backends/llamacpp_api.py
> +            raise backends.ContextExceededError(f"Context token limit for {self.model_spec.model_name} exceeded",
I suggest to raise this already in `check_context_limit` (see comment below). the brackets are also hard to read here.

2024-04-19 12:15 UTC, phisad commented on backends/utils.py
> +    return fits, tokens_used, tokens_left, context_size
`context_size` is an input parameter and does not need to be returned. And instead of returned two extract arguments the token_used and tokens_left should be in the error message. Maybe rename method into `assert_context_limit`

2024-04-19 12:15 UTC, phisad requested changes
see comments in code

2024-04-19 13:34 UTC, Gnurro commented on backends/llamacpp_api.py
> +    if hasattr(model_spec, 'execute_on'):
`execute_on` was David's suggestion, but it can be renamed to `device`.
Since llama.cpp/llama-cpp-python can be installed with other GPU hardware backends than CUDA, using "cuda" here would be misleading.

2024-04-19 13:36 UTC, Gnurro commented on backends/llamacpp_api.py
> +            gpu_layers_offloaded = -1
It is redundant - but the safe kind of redundancy.

2024-04-19 13:39 UTC, Gnurro commented on backends/llamacpp_api.py
> +                    # get BOS/EOS strings for chatml from llama.cpp:
Why?

2024-04-19 13:41 UTC, Gnurro commented on backends/llamacpp_api.py
> +        for key, value in self.model.metadata.items():
I can change it to that. The way I wrote is due to the metadata not being thoroughly standardized and me checking with prints during development.

2024-04-19 13:45 UTC, Gnurro commented on backends/llamacpp_api.py
> +            raise backends.ContextExceededError(f"Context token limit for {self.model_spec.model_name} exceeded",
It's raised here for easy access to the model name, so that it gets logged properly. If it's raised in the checking function, the model name would need to be passed to it as well. I can make that change, but it would mean to change this in HF backend as well.

I don't know what you mean with hard to read brackets here.

2024-04-19 13:48 UTC, Gnurro commented on backends/utils.py
> +    return fits, tokens_used, tokens_left, context_size
Context size is returned here so that it can be used when the exception is caught in custom Player/GameMaster classes. The idea is to leave it to the game developers how to handle their messages if the context would be exceeded, and providing all details about the context this way allows for flexibility.

2024-04-19 14:42 UTC, Gnurro commented on backends/llamacpp_api.py
> +        for key, value in self.model.metadata.items():
This does not work, as the key is not just `context_length`, but has a prefix for the model architecture. For example openchat_3.5-GGUF has the key `llama.context_length`. So it either also needs to get the model architecture from the metadata or remain in the loop with the `if "context_length in key`.

2024-04-19 15:35 UTC, davidschlangen commented on backends/llamacpp_api.py
> +    if hasattr(model_spec, 'execute_on'):
I find `execute_on` more transparent than `device`, but no strong feelings. `cuda` however would indeed be wrong as name for `gpu`, because kind of the whole point of `llama.cpp` is that it can make use of non-NVIDIA-GPUs.

2024-04-19 16:05 UTC, Gnurro commented
I've found an issue with custom chat template application (after excising the chat formatter part), I'll rework the generation method to work as intended. We can close the PR until that is done.

2024-04-20 09:44 UTC, phisad commented on backends/llamacpp_api.py
> +    if hasattr(model_spec, 'execute_on'):
OK, just wanted to bring this up. :) And "cuda" is only an example, it could also be "cpp" (or whatever is a good name here).

2024-04-20 09:44 UTC, phisad commented on backends/llamacpp_api.py
> +                    # get BOS/EOS strings for chatml from llama.cpp:
Because it is exactly what is written in code.

2024-04-20 09:45 UTC, phisad commented on backends/llamacpp_api.py
> +        for key, value in self.model.metadata.items():
OK, I feared that. Then stick to the loop.

2024-04-20 09:51 UTC, phisad commented on backends/llamacpp_api.py
> +            raise backends.ContextExceededError(f"Context token limit for {self.model_spec.model_name} exceeded",
Return of multiple variables can be done, but is hard to read `context_check[3]`. Then better return a named tuple: `check_results.max_tokens` or something. That this line needs a comment is a bad sign: `if not context_check[0]: # if context is exceeded, context_check[0] is False`.

If you need access to the model name (for logging), maybe move this method to Model.

2024-04-20 09:54 UTC, phisad commented on backends/utils.py
> +    return fits, tokens_used, tokens_left, context_size
Nah, here we talk about the check utility. And it does not throw an exception (yet)? So if game devs are supposed to catch the exception (and e.g. try re-prompting) then these details should become part of the exception as class attributes (not the return params here).

2024-04-20 09:56 UTC, phisad commented
> We can close the PR until that is done

No need to close this (from my side). You can continue using this branch.

2024-04-23 09:58 UTC, Gnurro commented on backends/llamacpp_api.py
> +        for key, value in self.model.metadata.items():
I'll rely on what *is* specified (https://github.com/ggerganov/ggml/blob/master/docs/gguf.md#required), which gets rid of the loop. Specific models need testing and setup if they are missing something (ie chat template) anyways, so if a model file does not follow the basic specification, I assume it'll be noticed then.

2024-04-24 13:42 UTC, Gnurro commented
Tested and working with a full benchmark run using openchat_3.5-GGUF-Q5. Should be ready to merge from my view.

2024-04-24 13:45 UTC, Gnurro commented on backends/llamacpp_api.py
> +    if hasattr(model_spec, 'execute_on'):
"gpu" and "cpu" match what the flag does accurately, and tie in with the need to install `llama-cpp-python` with matching `llama.cpp` hardware support.

2024-04-25 07:49 UTC, phisad approved these changes

2024-04-25 07:51 UTC, merged