Add model OpenAI gpt-4-vision-preview
clp-research/clemcore pull request #89
Opened 2024-05-06 14:32 UTC by yanweiser

I have extended the OpenAI backend and model_registry to support OpenAI's multimodal version of gpt-4. This also needed a small change to the way messages are added by allowing users to pass images (file path or link) to the add_message function via the optional keywork 'image'. I am using keyword arguments for this to make it easily extendable to other modalities (video, audio ...) and combinations of them. While most open models only support one image per user message, gpt-4v also takes multiple images in a single message. Hence the value of the 'image' argument needs to be a string or a list of strings. Since the format in which messages are passed to the model differes from other OpenAI models, I added a new value to the model_registry which indicated if this other messages format needs to be aplied.

2024-05-07 09:42 UTC, phisad requested changes

2024-05-07 09:42 UTC, phisad commented on clemgame/clemgame.py
> +            message['image'] = kwargs['image']
Would it make sense to already allow lists here?

2024-05-07 09:42 UTC, phisad commented on backends/openai_api.py
> +        self.is_vision = False
No need to introduce an attribute. Just use the model_spec where needed.

2024-05-07 09:42 UTC, phisad commented on clemgame/clemgame.py
> +    def add_user_message(self, player: Player, utterance: str, **kwargs: Dict):
Did you test this with no-vision model? Could this break backwards compatibility?

2024-05-07 09:42 UTC, phisad commented on backends/openai_api.py
> +            this = {"role": message["role"],
`this` is not a good variable name. Could be confused with `self`

2024-05-07 09:42 UTC, phisad commented on backends/openai_api.py
> +            if "image" in message.keys():
Isn't `in` already checking the dict keys?

2024-05-07 09:42 UTC, phisad commented on backends/openai_api.py
> +                                "url": loaded
This looks to me as the if could go into the "url" field directly: `"url": loaded if url else f"data:image/jpeg;base64,{loaded}"`

2024-05-07 10:57 UTC, yanweiser commented on clemgame/clemgame.py
> +    def add_user_message(self, player: Player, utterance: str, **kwargs: Dict):
I have tested both text-only and multimodal games on text-only models and did not encounter any issues. When playing text-only games nothing changes. When playing multimodal games, the `image` keyword in the `messages` dict is ignored by the chat templates or the openai API. 
Models I ran for tests: 
 - `vicuna-7b-v1.5` which uses a custom chat template
 - `zephyr-7b-alpha` which uses a prebuild chat template
 - `gpt-3.5-turbo-0125` which passes the entire dict to the API
This test is of course not exhaustive but I tried to cover a large spectrum with select choices.

2024-05-07 11:12 UTC, yanweiser commented on backends/openai_api.py
> +            this = {"role": message["role"],
changed it to `vision_message`

2024-05-07 11:12 UTC, yanweiser commented on backends/openai_api.py
> +            if "image" in message.keys():
Yes, removed .keys()

2024-05-07 11:18 UTC, yanweiser commented on backends/openai_api.py
> +                                "url": loaded
Good idea, I have shortened it down.

2024-05-07 11:19 UTC, yanweiser commented on clemgame/clemgame.py
> +            message['image'] = kwargs['image']
Right now both lists or strings can be passed which might make it more confusing that it has to be. We could make sure that if images (one or more) are added to the history, they need to be given as a list. The current implementation of the huggingface_multimodal_backend only supports images be given as strings, not lists of stings, which is why I wanted it to be possible to pass stings at least for now.

2024-05-15 10:05 UTC, closed without merging

2024-05-16 08:39 UTC, phisad commented
Hi @yanweiser did you close this because of the other PR?

2024-05-16 08:49 UTC, yanweiser commented
Oh yeah, I should have let you know. I talked to Sherzod yesterday and he has implemented a backend for multimodal model for gpt-4-vision and the new gpt-4o as well as the anthropic claude model. Instead of adding one model backend at a time he will just add them all later on.